startDelaySeconds: 0
jmxUrl: service:jmx:rmi:///jndi/rmi://kafka:9999/jmxrmi
lowercaseOutputName: true
lowercaseOutputLabelNames: true
rules:
  - pattern: "kafka.server<type=(.+), name=(.+)><>Value"
    name: kafka_server_$1_$2
    type: GAUGE

  # Consumer group lag, offset, etc.
  - pattern: "kafka.consumer<type=(.+), name=(.+)><>Value"
    name: kafka_consumer_$1_$2
    type: GAUGE

  # Generic metric extraction fallback
  - pattern: ".*"
    name: generic_metric
    type: GAUGE
